### ISSUE TITLE
Select communication method at compile time

### ISSUE THREAD

**Issue by wolfbert** [SV-Zanshin/BME280#10]
In methods getdata and putdata in BME280.h, the communication method (I2C, SPI, soft SPI) is chosen at run time. This causes the respective code and libraries always to be included, using valuable memory. 

My suggestion would be to select any or all of these methods by means of #define at compile time. For most users, a single method would suffice, while the default (to maintain compatibility and allow for multiple sensors with different comms methods) could be support for all three. 

What's your take on this? I'm happy to provide code once my board has arrived and works with the current version.

**Comment by SV-Zanshin** [comment]
The overhead of the I2C and SPI libraries is minimal and keeping both options open in the library keeps it simple. Many Arduino users wouldn't trust themselves to modify an #ifdef in a library's source code to active one or the other communications method. I didn't want to make 2 separate codebases as almost all of the functions are independent of the communications method.

I think I could put some #ifdef into the library but with the default of both communications methods left "on" but with the option of disabling two of the three. I'll look into that later this week.

**Comment by SV-Zanshin** [comment]
I've looked at the code again and with I2C plus hardware SPI and software SPI as options making the code select one by using "#ifdef" makes things too complicated. The communications is abstracted into just the getData and putData template functions and into the appropriate overloaded "begin()" calls, so if someone needs just one method and the space savings that are associated it is very easy remove the if-then-else clauses and unused communications code.
