### ISSUE TITLE
Bit mask off in BME280_Class::iirFilter?

### ISSUE THREAD

**Issue by wolfbert** [SV-Zanshin/BME280#9]
Hi, 
while waiting for my BME280 board to arrive (so I couldn't test yet), I've browsed through your library and may  have stumbled upon a glitch in BME280_Class::iirFilter.

According to the data sheet, table 26 on page 28 (also table 18 on page 25), IIR filter values are in bits 4,3,2 of the config register. In line 289 of BME280.cpp however, the bit mask is

`returnValue = returnValue&B11110001;                                 // Get control reg, mask IIR bits`

while all other register values are left or right shifted by 2 (as expected). Shouldn't it be

`returnValue = returnValue&B11100011;                                 // Get control reg, mask IIR bits`

or am I missing something here?

**Comment by SV-Zanshin** [comment]
Yes, you are correct - I missed the IIR bits by that 1-offset. I've corrected that in the code.
